### ISSUE TITLE
Issue with POST Request to OVH API Resulting in 500 Internal Server Error

### ISSUE THREAD

**Issue by theCrazylegs** [ovh/php-ovh#144]
Hello,

I am encountering an issue when trying to make a POST request to the OVH API using your PHP wrapper. I am attempting to add a new DNS record to a domain using the following code snippet:
```
php
Copy code
$return = $ovh->post('/domain/zone/monobargine.com/record', array(
    'fieldType' => 'A',
    'subDomain' => 'imgs',
    'target' => 'xxx.xxx.xxx.xxx',
    'ttl' => '30'
));
var_dump($return);
```

However, each time I execute this code, I receive a 500 Internal Server Error response from the OVH API. The error message indicates an internal server error (Server::InternalServerError) on the OVH side.

I have verified that other HTTP methods (GET, PUT, DELETE) work fine, and the POST method is allowed according to the credential rules (POST to /domain/zone*).

```
array (size=9)
  'allowedIPs' => null
  'applicationId' => int xxxxxxxxx
  'creation' => string '2024-01-04T17:50:13+01:00' (length=25)
  'credentialId' => int xxxxxxxx
  'expiration' => null
  'lastUse' => string '2024-01-05T11:46:31+01:00' (length=25)
  'ovhSupport' => boolean false
  'rules' => 
    array (size=5)
      0 => 
        array (size=2)
          'method' => string 'GET' (length=3)
          'path' => string '/domain/zone*' (length=13)
      1 => 
        array (size=2)
          'method' => string 'PUT' (length=3)
          'path' => string '/domain/zone*' (length=13)
      2 => 
        array (size=2)
          'method' => string 'POST' (length=4)
          'path' => string '/domain/zone*' (length=13)
      3 => 
        array (size=2)
          'method' => string 'DELETE' (length=6)
          'path' => string '/domain/zone*' (length=13)
      4 => 
        array (size=2)
          'method' => string 'GET' (length=3)
          'path' => string '/me*' (length=4)
  'status' => string 'validated' (length=9)
```

Here is the specific error message from my logs:

```
Jan  5 11:29:37 klppprlamp1 vhost_apache_monprivileges.com_error: [Fri Jan 05 11:29:37.640860 2024] [proxy_fcgi:error] [pid 3280467:tid 140454865479360] [client 82.65.94.210:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught GuzzleHttp\\Exception\\ServerException: Server error: `POST https://eu.api.ovh.com/1.0/domain/zone/monobargine.com/record` resulted in a `500 Internal Server Error` response:\n{"class":"Server::InternalServerError","message":"Internal server error"}\n in /var/www/sites/prod/monprivileges.com/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:113\nStack trace:\n#0 /var/www/sites/prod/monprivileges.com/vendor/guzzlehttp/guzzle/src/Middleware.php(72): GuzzleHttp\\Exception\\RequestException::create(Object(GuzzleHttp\\Psr7\\Request), Object(GuzzleHttp\\Psr7\\Response), NULL, Array, NULL)\n#1 /var/www/sites/prod/monprivileges.com/vendor/guzzlehttp/promises/src/Promise.php(209): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Response))\n#2 /var/www/sites/prod/monprivileges.com/vendor/guzzlehttp/promises/src/Promis....
```
I have also confirmed that my credentials and API keys are correct.

Could you please assist me in resolving this issue or provide any guidance on how to troubleshoot further?

Thank you for your help.

Best regards,
Crazy

**Comment by theCrazylegs** [comment]
response : 

'ttl' => '30' => **INTERGER** => **'ttl' => 30**
