### ISSUE TITLE
Client error

### ISSUE THREAD

**Issue by c3ph3us** [ovh/php-ovh#49]
with copy & paste i wanted to check X-Frame header options like this :

```
$client = new Client();
$client->setDefaultOption('timeout', 1);
//$client->setDefaultOption('headers', array('X-Frame-Options' => 'ALLOW'));
$client->setDefaultOption('headers', array('User-Agent' => 'api_client') );
```

but this give me an error : 

```
PHP Fatal error:  Uncaught TypeError: Argument 3 passed to GuzzleHttp\Client::request() must be of the type array, integer given, called in /vendor/guzzlehttp/guzzle/src/Client.php on line 87 and defined in /vendor/guzzlehttp/guzzle/src/Client.php:126
Stack trace:
/vendor/guzzlehttp/guzzle/src/Client.php(87): GuzzleHttp\Client->request('setDefaultOptio...', 'timeout', 1)
#1 loadKey.inc.php(10): GuzzleHttp\Client->__call('setDefaultOptio...', Array)
#2 content.php(5): include('/var/www/html/c...')
#3 {main}
  thrown in /var/www/html/ceph3us.pl/pad/mgm/srv/vendor/guzzlehttp/guzzle/src/Client.php on line 126
```

**Comment by rbeuque74** [comment]
Hello,
This issue is about the `timeout` line, and not the `X-Frame-Options` line.
This concerns a mis-usage of `Guzzle`, you should raise the issue on their side.

Closing as stalled. Feel free to reopen if still relevant.

Romain
