### ISSUE TITLE
Error generating docs in Mac Os X 10.13.6

### ISSUE THREAD

**Issue by abkrim** [ovh/php-ovh#86]
PHP 7.2.13 (cli)

1. Clone  git clone https://github.com/ovh/php-ovh.git
2. cd  php-ovh && composer update # (Some issues on shell)
3. Try to generate docs

```
 abkrim@iMac-2  ~/Sites/php-ovh   master  vendor/bin/phing phpdocs
Buildfile: /Users/abkrim/Sites/php-ovh/build.xml

ovh/ovh > clean:

   [delete] Deleting directory /Users/abkrim/Sites/php-ovh/docs

ovh/ovh > phpdocs:

    [mkdir] Created dir: /Users/abkrim/Sites/php-ovh/docs

BUILD FAILED
Doctrine\Common\Annotations\AnnotationException: [Semantical Error] The annotation "@JMS\Serializer\Annotation\Type" in property phpDocumentor\Configuration::$title does not exist, or could not be auto-loaded. in /Users/abkrim/Sites/php-ovh/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationException.php:54
Stack trace:
#0 /Users/abkrim/Sites/php-ovh/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(734): Doctrine\Common\Annotations\AnnotationException::semanticalError('The annotation ...')
#1 /Users/abkrim/Sites/php-ovh/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(663): Doctrine\Common\Annotations\DocParser->Annotation()
#2 /Users/abkrim/Sites/php-ovh/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/DocParser.php(354): Doctrine\Common\Annotations\DocParser->Annotations()
#3 /Users/abkrim/Sites/php-ovh/vendor/doctrine/annotations/lib/Doctrine/Common/Annotations/AnnotationReader.php(254): Doctrine\Common\Annotations\DocParser->parse('/**\n     * @var...', 'property phpDoc...')
#4 /Users/abkrim/Sites/php-ovh/vendor/jms/serializer/src/Metadata/Driver/AnnotationDriver.php(154): Doctrine\Common\Annotations\AnnotationReader->getPropertyAnnotations(Object(ReflectionProperty))
#5 /Users/abkrim/Sites/php-ovh/vendor/jms/metadata/src/MetadataFactory.php(107): JMS\Serializer\Metadata\Driver\AnnotationDriver->loadMetadataForClass(Object(ReflectionClass))
#6 /Users/abkrim/Sites/php-ovh/vendor/jms/serializer/src/GraphNavigator/DeserializationGraphNavigator.php(163): Metadata\MetadataFactory->getMetadataForClass('phpDocumentor\\C...')
#7 /Users/abkrim/Sites/php-ovh/vendor/jms/serializer/src/Serializer.php(249): JMS\Serializer\GraphNavigator\DeserializationGraphNavigator->accept(Object(SimpleXMLElement), Array)
#8 /Users/abkrim/Sites/php-ovh/vendor/jms/serializer/src/Serializer.php(178): JMS\Serializer\Serializer->visit(Object(JMS\Serializer\GraphNavigator\DeserializationGraphNavigator), Object(JMS\Serializer\XmlDeserializationVisitor), Object(JMS\Serializer\DeserializationContext), Object(SimpleXMLElement), 'xml', Array)
#9 /Users/abkrim/Sites/php-ovh/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Configuration/Loader.php(112): JMS\Serializer\Serializer->deserialize('<?xml version="...', 'phpDocumentor\\C...', 'xml')
#10 /Users/abkrim/Sites/php-ovh/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Configuration/Loader.php(62): phpDocumentor\Configuration\Loader->createConfigurationObject('/Users/abkrim/S...', '/Users/abkrim/S...', NULL, 'phpDocumentor\\C...')
#11 /Users/abkrim/Sites/php-ovh/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Configuration/ServiceProvider.php(82): phpDocumentor\Configuration\Loader->load('/Users/abkrim/S...', '/Users/abkrim/S...', 'phpDocumentor\\C...')
#12 /Users/abkrim/Sites/php-ovh/vendor/pimple/pimple/lib/Pimple.php(126): phpDocumentor\Configuration\ServiceProvider->phpDocumentor\Configuration\{closure}(Object(phpDocumentor\Application))
#13 /Users/abkrim/Sites/php-ovh/vendor/pimple/pimple/lib/Pimple.php(83): Pimple::{closure}(Object(phpDocumentor\Application))
#14 /Users/abkrim/Sites/php-ovh/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Application.php(254): Pimple->offsetGet('config')
#15 /Users/abkrim/Sites/php-ovh/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Application.php(67): phpDocumentor\Application->addLogging()
#16 /Users/abkrim/Sites/php-ovh/vendor/phpdocumentor/phpdocumentor/src/phpDocumentor/Bootstrap.php(62): phpDocumentor\Application->__construct(Object(Composer\Autoload\ClassLoader), Array)
#17 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/tasks/ext/phpdoc/PhpDocumentor2Wrapper.php(181): phpDocumentor\Bootstrap->initialize()
#18 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/tasks/ext/phpdoc/PhpDocumentor2Wrapper.php(256): PhpDocumentor2Wrapper->initializePhpDocumentor()
#19 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/tasks/ext/phpdoc/PhpDocumentor2Task.php(173): PhpDocumentor2Wrapper->run()
#20 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/UnknownElement.php(100): PhpDocumentor2Task->main()
#21 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/Task.php(283): UnknownElement->main()
#22 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/Target.php(336): Task->perform()
#23 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/Target.php(366): Target->main()
#24 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/Project.php(898): Target->performTasks()
#25 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/Project.php(868): Project->executeTarget('phpdocs')
#26 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/Phing.php(723): Project->executeTargets(Array)
#27 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/Phing.php(200): Phing->runBuild()
#28 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/classes/phing/Phing.php(347): Phing::start(Array, NULL)
#29 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/bin/phing.php(58): Phing::fire(Array)
#30 /Users/abkrim/Sites/php-ovh/vendor/phing/phing/bin/phing(14): require_once('/Users/abkrim/S...')
#31 {main}
Total time: 0.2090 seconds
```

Issues when composer update
```
Package kherge/version is abandoned, you should avoid using it. No replacement was suggested.
Package herrera-io/json is abandoned, you should avoid using it. Use kherge/json instead.
Package herrera-io/phar-update is abandoned, you should avoid using it. No replacement was suggested.
```

**Comment by rbeuque74** [comment]
Hello,
Closing as stalled. Feel free to reopen if still relevant.

Romain
